[
  #  ./theme.nix
  ./applications/emacs.nix
  ./applications/firefox.nix
  ./applications/neovim.nix
  ./autoupgrade.nix
  ./backup.nix
  ./development
  ./graphics
  ./homelab/adguard.nix
  ./homelab/logging.nix
  ./homelab/misc.nix
  ./homelab/web-server.nix
  ./options.nix
  ./profiles/base.nix
  ./profiles/laptop.nix
  ./profiles/server.nix
  ./profiles/webserver.nix
  ./profiles/work.nix
  ./scripts
  ./security/default.nix
  ./security/dns.nix
  ./shell
  ./tailscale.nix
  ./time.nix
  ./v12n.nix
  ./topology/home.nix
]
