[
  ./options.nix
  #  ./theme.nix
  ./development
  ./graphics
  ./applications/firefox.nix
  ./applications/neovim.nix
  ./applications/emacs.nix
  ./profiles/base.nix
  ./profiles/laptop.nix
  ./security
  ./shell
  ./scripts
  ./tailscale
  ./caddy
  ./v18n
  ./homelab/adguard.nix
  ./homelab/web-server.nix
  ./homelab/misc.nix
]
