[
  #  ./theme.nix
  ./applications/amateur.nix
  ./applications/emacs.nix
  ./applications/firefox.nix
  ./applications/neovim.nix
  ./applications/chromium.nix
  ./autoupgrade.nix
  ./backup.nix
  ./development
  ./graphics
  ./home-server
  ./networking
  ./o11y
  ./options.nix
  ./productivity
  ./profiles
  ./scripts
  ./security
  ./shell
  ./topology/home.nix
]
