{
 "title": "NTP",
 "description": "Dashboard for chrony or OpenNTPD.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ip", "label": "NTP Pool IP Address", "query": "127.0.0.1" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_boot_time_seconds, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Leap second status",
   "type": "singlestat",
   "description": "This is the leap status, which can be Normal, Insert a second, Delete a second or Not synchronised.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Leap seconds status",
     "expr": "node_ntp_leap{job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"leap_status\"  FROM (SELECT \"leap_status\", \"system_time\" FROM \"chrony\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clock Synchronisation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_timex_sync_status{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Stratum",
   "type": "singlestat",
   "description": "The stratum indicates how many hops away from a computer with an attached reference clock we are. Such a computer is a stratum-1 computer, so the computer in the example is two hops away (i.e. foo.example.net is a stratum-2 and is synchronised from a stratum-1)",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Stratum",
     "expr": "node_ntp_stratum{job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chrony",
     "query": "SELECT \"stratum\"  FROM (SELECT \"stratum\", \"system_time\" FROM \"chrony\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "stratum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sanity check",
   "type": "singlestat",
   "description": "Aggregate NTPD health including stratum, leap flag, sane freshness, root distance being less than collector.ntp.max-distance and causality violation being less than collector.ntp.local-offset-tolerance.\n\nCausality violation is lower bound estimate of clock error done using SNTP, it's calculated as positive portion of abs(node_ntp_offset) - node_ntp_rtt / 2.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Reference ID",
     "expr": "node_ntp_sanity{job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chrony",
     "query": "SELECT \"reference_id\"  FROM (SELECT \"reference_id\", \"system_time\" FROM \"chrony\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "stratum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ntppool status",
   "type": "text",
   "description": "The Score graph - Blue/red \"double size\" dots are points/scores (using the right axis). A couple of times an hour the pool system checks the time from your server and compares it to the local time. Points are deducted if the server can’t be reached or if the time offset is more than 100ms (as measured from the monitoring systems). More points are deducted the bigger the offset is.\n\n\nThe Offset graph - Green/orange/red small dots are offsets (in milliseconds, using the left axis). The monitoring system works roughly like an SNTP (RFC 2030) client, so it is more susceptible by random network latencies between the server and the monitoring system than a regular ntpd server would be.\n\nThe monitoring system can be inaccurate as much as 10ms or more.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "content": "<a href=\"http://www.pool.ntp.org/scores/$ip\">\n  <img src=\"http://graphs.ntppool.net/graph/$ip/offset.png\" style=\"margin:0 auto; display:block\">\n</a>"
  },
  {
   "title": "Offset",
   "type": "graph",
   "description": "Offset - This is the estimated local offset to the ntp sources on the last clock update.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Last Offset",
     "expr": "node_ntp_offset_seconds{job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Offset",
     "measurement": "chrony",
     "select": [
      [
       { "params": [ "last_offset" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Round-Trip Time",
   "type": "graph",
   "description": "RTT (round-trip time) from node_exporter collector to local NTPD. This value is used in sanity check as part of causality violation estimate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Frequency",
     "expr": "node_ntp_rtt_seconds{job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "RTT",
     "measurement": "chrony",
     "select": [
      [
       { "params": [ "frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sources",
   "type": "graph",
   "description": "Root delay - This is the total of the network path delays to the stratum-1 computer from which the computer is ultimately synchronised. In certain extreme situations, this value can be negative. (This can arise in a symmetric peer arrangement where the computers’ frequencies are not tracking each other and the network delay is very short relative to the turn-around time at each computer.)\n\nRoot dispersion - This is the total dispersion accumulated through all the computers back to the stratum-1 computer from which the computer is ultimately synchronised. Dispersion is due to system clock resolution, statistical measurement variations etc. An absolute bound on the computer’s clock accuracy. (The estimate of the total amount of error/variance between that server and the correct time.)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Root delay",
     "expr": "node_ntp_root_delay_seconds{job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Root Delay",
     "measurement": "chrony",
     "select": [
      [
       { "params": [ "root_delay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Root dispersion",
     "expr": "node_ntp_root_dispersion_seconds{job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Root Dispersion",
     "measurement": "chrony",
     "select": [
      [
       { "params": [ "root_dispersion" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Clock Adjustment",
   "type": "graph",
   "description": "Reference Time. This field show time when the last adjustment was made, but implementation details vary from \"local wall-clock time\" to \"Reference Time field in incoming SNTP packet\".\n\nrepresent some estimate of \"freshness\" of synchronization.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "node_time_seconds - node_ntp_reference_timestamp_seconds{job=~\"$job\"}",
     "legendFormat": "Last Adjustment "
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "graph",
   "description": "The ‘frequency’ is the rate by which the system’s clock would be wrong if the NTP client was not correcting it. It is expressed in ppm (parts per million). For example, a value of 1 ppm would mean that when the system’s clock thinks it has advanced 1 second, it has actually advanced by 1.000001 seconds relative to true time.\n\nIt is the frequency the local clock is adjusted by the NTP client to correct the local time.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "expr": "node_timex_frequency_adjustment_ratio{job=~\"$job\"}-1",
     "legendFormat": "Local clock frequency adjustment (0 = no change)"
    }
   ]
  },
  {
   "title": "Max Error",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_maxerror_seconds{job=~\"$job\"}",
     "legendFormat": "Maximum error in seconds"
    }
   ]
  },
  {
   "title": "Estimated Error",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{job=~\"$job\"}",
     "legendFormat": "Estimated error in seconds"
    }
   ]
  }
 ]
}